In [ ]:
import pandas as pd
Variables={
    "y":[78.5,74.3,104.3,87.6,95.9,109.2,102.7,72.5,93.1,115.9,83.8,113.3,109.4],
    "X1":[7,1,11,11,7,11,3,1,2,21,1,11,10],
    "X2":[26,29,56,31,52,55,71,31,54,47,40,66,68],
    "X3":[6,15,8,8,6,9,17,22,18,4,23,9,8],
    "X4":[60,52,20,47,33,22,6,44,22,26,34,12,12]}

df=pd.DataFrame(Variables)
print(df)

        y  X1  X2  X3  X4
0    78.5   7  26   6  60
1    74.3   1  29  15  52
2   104.3  11  56   8  20
3    87.6  11  31   8  47
4    95.9   7  52   6  33
5   109.2  11  55   9  22
6   102.7   3  71  17   6
7    72.5   1  31  22  44
8    93.1   2  54  18  22
9   115.9  21  47   4  26
10   83.8   1  40  23  34
11  113.3  11  66   9  12
12  109.4  10  68   8  12


In [ ]:
import pandas as pd
import numpy as np

Variables={
    "y":[78.5,74.3,104.3,87.6,95.9,109.2,102.7,72.5,93.1,115.9,83.8,113.3,109.4],
    "X1":[7,1,11,11,7,11,3,1,2,21,1,11,10],
    "X2":[26,29,56,31,52,55,71,31,54,47,40,66,68],
    "X3":[6,15,8,8,6,9,17,22,18,4,23,9,8],
    "X4":[60,52,20,47,33,22,6,44,22,26,34,12,12]}

df=pd.DataFrame(Variables)

# Create a copy of the DataFrame to manipulate
X_processed = df.copy()

# Add a column of ones for the intercept term
X_processed.insert(0, 'intercept', 1)

# Drop the 'y' column as requested
X_processed = X_processed.drop(columns=['y'])

# Convert the processed DataFrame to a NumPy matrix
X_matrix = X_processed.values

print("Matrix with a column of ones (without 'y' column):")
print(X_matrix)

Matrix with a column of ones (without 'y' column):
[[ 1  7 26  6 60]
 [ 1  1 29 15 52]
 [ 1 11 56  8 20]
 [ 1 11 31  8 47]
 [ 1  7 52  6 33]
 [ 1 11 55  9 22]
 [ 1  3 71 17  6]
 [ 1  1 31 22 44]
 [ 1  2 54 18 22]
 [ 1 21 47  4 26]
 [ 1  1 40 23 34]
 [ 1 11 66  9 12]
 [ 1 10 68  8 12]]


In [ ]:
# Calculate the transpose of the matrix
X_matrix_transpose = X_matrix.T

print("Transpose of the matrix:")
print(X_matrix_transpose)

Transpose of the matrix:
[[ 1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 7  1 11 11  7 11  3  1  2 21  1 11 10]
 [26 29 56 31 52 55 71 31 54 47 40 66 68]
 [ 6 15  8  8  6  9 17 22 18  4 23  9  8]
 [60 52 20 47 33 22  6 44 22 26 34 12 12]]


In [ ]:
# Extract the 'y' column as a column vector
y_vector = df['y'].values.reshape(-1, 1)

print("Vector 'y':")
print(y_vector)

Vector 'y':
[[ 78.5]
 [ 74.3]
 [104.3]
 [ 87.6]
 [ 95.9]
 [109.2]
 [102.7]
 [ 72.5]
 [ 93.1]
 [115.9]
 [ 83.8]
 [113.3]
 [109.4]]


In [ ]:
# Multiply the transpose of the matrix by the original matrix
result_matrix_multiplication = np.dot(X_matrix_transpose, X_matrix)

print("Result of X_matrix_transpose * X_matrix:")
print(result_matrix_multiplication)

Result of X_matrix_transpose * X_matrix:
[[   13    97   626   153   390]
 [   97  1139  4922   769  2620]
 [  626  4922 33050  7201 15739]
 [  153   769  7201  2293  4628]
 [  390  2620 15739  4628 15062]]


In [ ]:
# Calculate the inverse of the result_matrix_multiplication
inverse_matrix = np.linalg.inv(result_matrix_multiplication)

print("Inverse of result_matrix_multiplication:")
print(inverse_matrix)

Inverse of result_matrix_multiplication:
[[ 8.20654575e+02 -8.44180186e+00 -8.45777985e+00 -8.63453878e+00
  -8.28974378e+00]
 [-8.44180186e+00  9.27104019e-02  8.56862094e-02  9.26373566e-02
   8.44549553e-02]
 [-8.45777985e+00  8.56862094e-02  8.75602572e-02  8.78666397e-02
   8.55980995e-02]
 [-8.63453878e+00  9.26373566e-02  8.78666397e-02  9.52014097e-02
   8.63919188e-02]
 [-8.28974378e+00  8.44549553e-02  8.55980995e-02  8.63919188e-02
   8.40311912e-02]]


In [ ]:
# Calculate betas: (X'X)^-1 * X'y
betas = np.dot(np.dot(inverse_matrix, X_matrix_transpose), y_vector)

print("Beta coefficients:")
print(betas)

Beta coefficients:
[[62.4053693 ]
 [ 1.55110265]
 [ 0.51016758]
 [ 0.1019094 ]
 [-0.14406103]]
